apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: payments
  labels:
    app: billing-service
    platform.northwindpay.io/observability: request-correlation
    platform.northwindpay.io/architecture-layer: domain
    platform.northwindpay.io/event-contract: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
        platform.northwindpay.io/observability: request-correlation
        platform.northwindpay.io/architecture-layer: domain
        platform.northwindpay.io/event-contract: v1
      annotations:
        platform.northwindpay.io/request-id-header: X-Request-Id
        platform.northwindpay.io/log-format: json-structured
    spec:
      containers:
        - name: billing-service
          image: registry.northwindpay.internal/billing-service:1.0.1
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: northwind-platform-env
          env:
            - name: PORT
              value: "3002"
            - name: SERVICE_NAME
              value: billing-service
            - name: ARCHITECTURE_LAYER
              value: domain
            - name: EVENT_CONTRACT_VERSION
              value: v1
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: northwind-platform-env
                  key: LOG_LEVEL
            - name: REQUEST_ID_HEADER
              valueFrom:
                configMapKeyRef:
                  name: northwind-platform-env
                  key: REQUEST_ID_HEADER
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: billing-db
                  key: url
          readinessProbe:
            httpGet:
              path: /ready
              port: 3002
              httpHeaders:
                - name: X-Request-Id
                  value: k8s-readiness-probe
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: payments
  labels:
    app: billing-service
spec:
  selector:
    app: billing-service
  ports:
    - port: 3002
      targetPort: 3002
