apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-service
  namespace: payments
  labels:
    app: webhook-service
    platform.northwindpay.io/observability: request-correlation
    platform.northwindpay.io/architecture-layer: domain
    platform.northwindpay.io/event-contract: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webhook-service
  template:
    metadata:
      labels:
        app: webhook-service
        platform.northwindpay.io/observability: request-correlation
        platform.northwindpay.io/architecture-layer: domain
        platform.northwindpay.io/event-contract: v1
      annotations:
        platform.northwindpay.io/request-id-header: X-Request-Id
    spec:
      containers:
        - name: webhook-service
          image: registry.northwindpay.internal/webhook-service:1.0.1
          ports:
            - containerPort: 3003
          envFrom:
            - configMapRef:
                name: northwind-platform-env
          env:
            - name: PORT
              value: "3003"
            - name: SERVICE_NAME
              value: webhook-service
            - name: ARCHITECTURE_LAYER
              value: domain
            - name: EVENT_CONTRACT_VERSION
              value: v1
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: northwind-platform-env
                  key: LOG_LEVEL
            - name: REQUEST_ID_HEADER
              valueFrom:
                configMapKeyRef:
                  name: northwind-platform-env
                  key: REQUEST_ID_HEADER
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: webhook-db
                  key: url
          readinessProbe:
            httpGet:
              path: /ready
              port: 3003
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: payments
spec:
  selector:
    app: webhook-service
  ports:
    - port: 3003
      targetPort: 3003
